language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install pipenv flake8 pylint
  - make init

# command to run tests
script:
  - make test
  - pipenv run flake8 --max-line-length=99 # pylint is too aggresive to fail the lint step
